const LEVELS = [
 {id:1,title:'De Hiërogliefen',topic:'Hiërogliefen herkennen',fact:'Hiërogliefen konden klanken, woorden en begrippen weergeven.',image:'assets/images/image10.jpeg',reward:{name:'Bronzen sleutel',icon:'🗝️',history:'Deze spelsleutel verwijst naar de houten pensloten die de oude Egyptenaren gebruikten om deuren te beveiligen.'},hint:'Begin met de herkenbare symbolen: de zonneschijf staat voor zon en de golfjes voor water.',type:'matching'},
 {id:2,title:'De Tijdlijn',topic:'Egyptische perioden ordenen',fact:'Het Oude Rijk kwam vóór het Middenrijk en het Nieuwe Rijk; Cleopatra leefde veel later.',image:'assets/images/image11.jpeg',reward:{name:'Scarabee',icon:'🪲',history:'De scarabee stond in het Oude Egypte symbool voor wedergeboorte en de dagelijks opkomende zon.'},hint:'Cleopatra leefde veel later dan de drie Egyptische rijken.',type:'timeline'},
 {id:3,title:'Farao of niet?',topic:'Rollen in de Egyptische samenleving',fact:'Farao’s bestuurden, priesters verzorgden rituelen en schrijvers hielden de administratie bij.',image:'assets/images/image12.jpeg',reward:{name:'Fakkel',icon:'🔥',history:'De fakkel staat in het spel voor kunstlicht; oude Egyptenaren gebruikten hiervoor onder andere olielampen.'},hint:'Een farao droeg de dubbele kroon en bestuurde het rijk.',type:'quiz'},
 {id:4,title:'De Piramide',topic:'De route door een piramide',fact:'Gangen en galerijen verbonden de ingang met kamers die dieper in de piramide lagen.',image:'assets/images/image13.jpeg',reward:{name:'Touw',icon:'🪢',history:'Egyptische landmeters en bouwers gebruikten touw om afstanden, rechte lijnen en hoeken uit te zetten.'},hint:'De ingang zit aan de buitenzijde; de grafkamer juist diep in het bouwwerk.',type:'pyramid'},
 {id:5,title:'De Goden',topic:'Egyptische goden en kenmerken',fact:'Ra hoorde bij de zon, Anubis bij de dodenwereld en Horus werd vaak als valk afgebeeld.',image:'assets/images/image14.jpeg',reward:{name:'Ankh',icon:'☥',history:'De ankh was het Egyptische symbool voor leven en werd ook verbonden met het eeuwige leven.'},hint:'Ra hoort bij de zon; Horus wordt vaak als valk afgebeeld.',type:'memory'},
 {id:6,title:'Mummificatie',topic:'De stappen van mummificatie',fact:'Organen werden verwijderd en het lichaam werd met natron gedroogd voordat het in linnen werd gewikkeld.',image:'assets/images/image15.jpeg',reward:{name:'Canopische kruik',icon:'🏺',history:'In canopische kruiken werden organen van een overledene bewaard tijdens het mummificatieproces.'},hint:'Eerst wordt het lichaam voorbereid, pas daarna gewikkeld en in de sarcofaag gelegd.',type:'sequence'},
 {id:7,title:'Schattenkamer',topic:'Egyptische grafgiften onderzoeken',fact:'Grafgiften werden meegegeven omdat men geloofde dat de overledene ze in het hiernamaals kon gebruiken.',image:'assets/images/image16.jpeg',reward:{name:'Gouden oog',icon:'𓂀',history:'Het Oog van Horus was een beschermend symbool dat ook stond voor herstel en gezondheid.'},hint:'Vergelijk de vier hoeken en kijk daarna naar het midden.',type:'differences'},
 {id:8,title:'Rekenen als een Egyptenaar',topic:'Egyptische getalsymbolen gebruiken',fact:'De Egyptenaren gebruikten afzonderlijke tekens voor onder andere 1, 10 en 100.',image:'assets/images/image17.jpeg',reward:{name:'Kristal',icon:'💎',history:'Egyptenaren verwerkten glanzende mineralen en edelstenen in sieraden en amuletten voor status en bescherming.'},hint:'Een boog is 10 en een streep is 1.',type:'numbers'},
 {id:9,title:'Los het raadsel op...',topic:'Kernbegrippen uit het Oude Egypte',fact:'De Nijl leverde water en vruchtbare grond en was daardoor onmisbaar voor het leven in Egypte.',image:'assets/images/image18.jpeg',reward:{name:'Tempelsleutel',icon:'🔑',history:'Deze spelsleutel symboliseert toegang tot Egyptische tempels, heilige plaatsen voor godenverering en rituelen.'},hint:'Het bouwwerk heeft het lichaam van een leeuw en een mensenhoofd.',type:'riddle'},
 {id:10,title:'De Kamer van de Farao',topic:'Historische voorwerpen duiden',fact:'De ankh, scarabee, canopische kruik en het Oog van Horus hadden elk een herkenbare functie of betekenis.',image:'assets/images/image19.jpeg',reward:null,hint:'Plaats de voorwerpen in dezelfde volgorde als de kamers waarin je ze vond.',type:'final'}
];
